server:
  port: 8090
spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521/orcl
    username: lyr
    password: lyr
    driver-class-name: oracle.jdbc.driver.OracleDriver
  devtools:
    restart:
      enabled: true
      exclude: templates
  thymeleaf:
    cache: false


  jpa:
    show-sql: true